---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default # Optional, specify if needed
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: mycred
      containers:
        - name: myapp
          image: abayomi2/cici_working:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myloadbalancer
  namespace: default # Optional, specify if needed
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - port: 80
      name: http
      targetPort: 8080
