---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: abe
spec:
  replicas: 2
  minReadySeconds: 10  # Wait for 10 seconds before deploying the next pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1  # Max number of pods to run for the deployment
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: mycred
      containers:
        - name: myapp
          image: abayomi2/cici_working:13_03_25
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myloadbalancer
  namespace: abe
  labels:
    app: myapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: myapp
